package services;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.reflect.TypeToken;
import models.AIQuestion;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

/**
 * High-level service used by controllers to request quiz generation and parse the AI response.
 */
public class QuizGenerationService {

    private final GeminiApiClient client;
    private final Gson gson = new Gson();

    public QuizGenerationService() {
        this.client = new GeminiApiClient();
    }

    /**
     * Generate questions using the Gemini API.
     * @param topic topic text
     * @param difficulty Easy/Medium/Hard
     * @param count number of questions
     * @return list of AIQuestion
     */
    public List<AIQuestion> generate(String topic, String difficulty, int count) throws IOException, InterruptedException, GeminiApiClient.GeminiClientException {
        String prompt = buildPrompt(topic, difficulty, count);

        // Send the human-readable prompt text to the Gemini client; the client will wrap it in
        // the Google `contents.parts.text` body expected by generateContent.
        String raw = client.generate(prompt);

        // Gemini generateContent usually returns a wrapper object; unwrap generated text first.
        String generatedText = extractGeneratedText(raw);
        String normalized = normalizeGeneratedText(generatedText != null ? generatedText : raw);

        // Try to parse as an array of objects. The AI is instructed to return only valid JSON array.
        try {
            JsonElement root = JsonParser.parseString(normalized);
            List<AIQuestion> list = new ArrayList<>();

            if (root.isJsonArray()) {
                JsonArray arr = root.getAsJsonArray();
                Type type = new TypeToken<List<AIQuestion>>(){}.getType();
                list = gson.fromJson(arr, type);
            } else if (root.isJsonObject()) {
                // some APIs wrap the result; try to extract a field that looks like content
                if (root.getAsJsonObject().has("choices")) {
                    JsonElement choices = root.getAsJsonObject().get("choices");
                    Type type = new TypeToken<List<AIQuestion>>(){}.getType();
                    list = gson.fromJson(choices, type);
                } else if (root.getAsJsonObject().has("output")) {
                    JsonElement out = root.getAsJsonObject().get("output");
                    // assume output may contain a JSON string
                    String inside = out.getAsString();
                    list = parseFromString(inside);
                } else {
                    // try to convert single object into a one-element list
                    AIQuestion q = gson.fromJson(root, AIQuestion.class);
                    list.add(q);
                }
            }

            list.removeIf(q -> q == null || isBlank(q.getQuestion()));
            if (list.isEmpty()) {
                throw new RuntimeException("Gemini returned no usable questions. Raw response:\n" + raw);
            }

            return list;
        } catch (Exception ex) {
            // Try a forgiving parse: maybe the AI returned a string containing JSON array
            try {
                List<AIQuestion> fallback = parseFromString(normalized);
                fallback.removeIf(q -> q == null || isBlank(q.getQuestion()));
                if (!fallback.isEmpty()) {
                    return fallback;
                }
            } catch (RuntimeException rex) {
                // As a last resort, try to extract the first JSON array substring from the response text
                int a = normalized.indexOf('[');
                int b = normalized.lastIndexOf(']');
                if (a >= 0 && b > a) {
                    String sub = normalized.substring(a, b + 1);
                    List<AIQuestion> fallback = parseFromString(sub);
                    fallback.removeIf(q -> q == null || isBlank(q.getQuestion()));
                    if (!fallback.isEmpty()) {
                        return fallback;
                    }
                }
                throw new RuntimeException("Failed to parse AI response: " + ex.getMessage() + "\nRaw response:\n" + raw, ex);
            }
        }

        throw new RuntimeException("Failed to parse AI response into usable quiz questions. Raw response:\n" + raw);
    }

    /** Extracts the actual text generated by Gemini from the generateContent wrapper. */
    private String extractGeneratedText(String raw) {
        try {
            JsonElement root = JsonParser.parseString(raw);
            if (!root.isJsonObject()) {
                return raw;
            }
            JsonObject obj = root.getAsJsonObject();
            if (!obj.has("candidates")) {
                return raw;
            }
            JsonArray candidates = obj.getAsJsonArray("candidates");
            if (candidates.size() == 0) {
                return raw;
            }
            JsonObject candidate0 = candidates.get(0).getAsJsonObject();
            if (!candidate0.has("content")) {
                return raw;
            }
            JsonObject content = candidate0.getAsJsonObject("content");
            if (!content.has("parts")) {
                return raw;
            }
            JsonArray parts = content.getAsJsonArray("parts");
            if (parts.size() == 0) {
                return raw;
            }
            JsonObject part0 = parts.get(0).getAsJsonObject();
            if (part0.has("text")) {
                return part0.get("text").getAsString();
            }
        } catch (Exception ignored) {
            // fall through to raw text
        }
        return raw;
    }

    private String normalizeGeneratedText(String text) {
        if (text == null) {
            return "";
        }
        String s = text.trim();
        // strip common markdown fences that LLMs sometimes include
        if (s.startsWith("```")) {
            int firstNewline = s.indexOf('\n');
            if (firstNewline >= 0) {
                s = s.substring(firstNewline + 1).trim();
            }
            if (s.endsWith("```")) {
                s = s.substring(0, s.length() - 3).trim();
            }
        }
        return s;
    }

    private boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }

    private List<AIQuestion> parseFromString(String s) {
        try {
            Type type = new TypeToken<List<AIQuestion>>(){}.getType();
            return gson.fromJson(s, type);
        } catch (Exception e) {
            // give a clear exception to caller by wrapping in runtime exception
            throw new RuntimeException("Failed to parse AI response into questions: " + e.getMessage() + "\nResponse:\n" + s, e);
        }
    }

    private String buildPrompt(String topic, String difficulty, int count) {
        StringBuilder sb = new StringBuilder();
        sb.append("Generate ").append(count).append(" multiple choice questions about ");
        sb.append(topic).append(".\n\n");
        sb.append("Requirements:\n");
        sb.append("- difficulty: ").append(difficulty.toLowerCase()).append("\n");
        sb.append("- each question must have exactly 4 answer choices\n");
        sb.append("- indicate which choice is correct (return a letter A/B/C/D)\n");
        sb.append("- include a short explanation for the correct answer\n");
        sb.append("- Return ONLY valid JSON in this exact format:\n");
        sb.append("[\n  {\n    \"question\": \"...\",\n    \"choices\": [\"...\", \"...\", \"...\", \"...\"],\n    \"correctAnswer\": \"A\",\n    \"explanation\": \"...\"\n  }\n]\n");

        return sb.toString();
    }
}




